# Generated by Django 2.2.7 on 2019-12-07 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petdocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Breed', verbose_name='Порода')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petdocs.Registration', verbose_name='Регистрационный документ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petdocs.Owner', verbose_name='Владелец')),
            ],
        ),
    ]
