# Generated by Django 2.2.7 on 2019-12-22 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pets_photo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_registration', to='petdocs.Registration', verbose_name='Регистрационный документ'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petdocs.Owner', verbose_name='Владелец'),
        ),
    ]
