# Generated by Django 2.2.7 on 2019-12-19 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20191207_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_registration', to='petdocs.Registration', verbose_name='Регистрационный документ'),
        ),
    ]
