# Generated by Django 2.2.7 on 2019-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cage',
            field=models.CharField(default=None, max_length=10, verbose_name='Номер клетки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_num',
            field=models.CharField(auto_created=True, blank=True, max_length=256, null=True, verbose_name='Регистрационный номер'),
        ),
    ]
