# Generated by Django 2.2.7 on 2019-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cage',
            field=models.CharField(default=None, max_length=10, verbose_name='Номер клетки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_num',
            field=models.CharField(default=None, max_length=256, verbose_name='Регистрационный номер'),
            preserve_default=False,
        ),
    ]
