# Generated by Django 2.2.7 on 2019-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdocs', '0002_auto_20191219_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_num',
            field=models.CharField(auto_created=True, max_length=256, verbose_name='Регистрационный номер'),
        ),
    ]
